### ISSUE TITLE
Crash in RFTools Dim

### ISSUE THREAD

**Issue by ijo42** [micdoodle8/MicdoodleCore#14]
CrashLog: https://hastebin.com/ubifuzuyec.py
I create a default rftools dim and build giant railroading and in one moment my server is downed and i can't join because they crash each on each and i clear player data and it work but.. thats not good
All versions on hastebin

**Comment by radfast** [comment]
That hastebin is empty?   Please provide the crashlog.

**Comment by ijo42** [comment]
Oops, https://pastebin.com/Sy3gH15f

**Comment by radfast** [comment]
Thanks for reporting.  There's no conflict with RF Tools dimension here.  There is a bug in some error reporting code we recently added in Galacticraft build 234, it works fine in single player but crashes a dedicated server.  This will be fixed in next build 237, see https://github.com/micdoodle8/Galacticraft/commit/13be525dcec98e6b79edc2d897b7ee1ea966169d.

What the (bugged) error reporting code would be reporting, in your game, is a Biome ID conflict.  One of your other mods - I don't know which - has overlapping Biome IDs with Galacticraft.  Galacticraft by default wants to use Biome IDs 102-105.  See the configuration file `core.conf`, the setting `BiomeIDBase`.

If you can fix the Biome ID conflict now, then your game will not crash, even with GC build 234.

Or, if you wait for GC build 237, then check logs for a message like this: "POTENTIAL BIOME ID CONFLICT for id 104 conflicting with Galacticraft", this will tell you the ID with the problem.
